### ISSUE TITLE
Show counts within badge

### ISSUE THREAD

**Issue by oyeanuj** [ntamas/react-badger#1]
Hi @ntamas, thanks for creating this library. I am wondering if you plan to provide an option to display count within the badge? That would be super useful to a lot of people since it is somewhat of standard notification practice.

**Comment by ntamas** [comment]
This was sort-of-supported already as the children of the `<Badge>` component were forwarded to the `<div>` that was generated from the badge. However, there was a bug in setting the `line-height` style of the badge, which prevented this from working properly. I have fixed it in version 1.2.1 so feel free to upgrade to that and then you'll get the badge count feature. I have also updated the example.

**Comment by oyeanuj** [comment]
@ntamas Thanks for the quick response!
